import { registerThemesHandlers } from "../pro/main/ipc/handlers/themes_handlers";
import { registerVisualEditingHandlers } from "../pro/main/ipc/handlers/visual_editing_handlers";

import { registerAppHandlers } from "./handlers/app_handlers";
import { registerAppUpgradeHandlers } from "./handlers/app_upgrade_handlers";
import { registerAuthHandlers } from "./handlers/auth_handlers";
import { registerCapacitorHandlers } from "./handlers/capacitor_handlers";
import { registerChatHandlers } from "./handlers/chat_handlers";
import { registerChatStreamHandlers } from "./handlers/chat_stream_handlers";
import { registerContextPathsHandlers } from "./handlers/context_paths_handlers";
import { registerDebugHandlers } from "./handlers/debug_handlers";
import { registerDependencyHandlers } from "./handlers/dependency_handlers";
import { registerDesignSystemHandlers } from "./handlers/design_system_handlers";
import { registerEntitlementHandlers } from "./handlers/entitlement_handlers";
import { registerFreeAgentQuotaHandlers } from "./handlers/free_agent_quota_handlers";
import { registerGithubBranchHandlers } from "./handlers/git_branch_handlers";
import { registerGithubHandlers } from "./handlers/github_handlers";
import { registerHelpBotHandlers } from "./handlers/help_bot_handlers";
import { registerImportHandlers } from "./handlers/import_handlers";
import { registerLanguageModelHandlers } from "./handlers/language_model_handlers";
import { registerLocalModelHandlers } from "./handlers/local_model_handlers";
import { registerMcpHandlers } from "./handlers/mcp_handlers";
import { registerNodeHandlers } from "./handlers/node_handlers";
import { registerPlanHandlers } from "./handlers/plan_handlers";
import { registerPortalHandlers } from "./handlers/portal_handlers";
import { registerProHandlers } from "./handlers/pro_handlers";
import { registerProblemsHandlers } from "./handlers/problems_handlers";
import { registerPromptHandlers } from "./handlers/prompt_handlers";
import { registerProposalHandlers } from "./handlers/proposal_handlers";
import { registerReleaseNoteHandlers } from "./handlers/release_note_handlers";
import { registerSecurityHandlers } from "./handlers/security_handlers";
import { registerSessionHandlers } from "./handlers/session_handlers";
import { registerSettingsHandlers } from "./handlers/settings_handlers";
import { registerShellHandlers } from "./handlers/shell_handler";
import { registerSupabaseHandlers } from "./handlers/supabase_handlers";
import { registerTemplateHandlers } from "./handlers/template_handlers";
import { registerTokenCountHandlers } from "./handlers/token_count_handlers";
import { registerUploadHandlers } from "./handlers/upload_handlers";
import { registerVercelHandlers } from "./handlers/vercel_handlers";
import { registerVersionHandlers } from "./handlers/version_handlers";
import { registerWindowHandlers } from "./handlers/window_handlers";

export function registerIpcHandlers() {
  // Register all IPC handlers by category
  registerAppHandlers();
  registerChatHandlers();
  registerChatStreamHandlers();
  registerSettingsHandlers();
  registerShellHandlers();
  registerDependencyHandlers();
  registerGithubHandlers();
  registerGithubBranchHandlers();
  registerVercelHandlers();
  registerNodeHandlers();
  registerProblemsHandlers();
  registerProposalHandlers();
  registerDebugHandlers();
  registerSupabaseHandlers();
  registerLocalModelHandlers();
  registerTokenCountHandlers();
  registerWindowHandlers();
  registerUploadHandlers();
  registerVersionHandlers();
  registerLanguageModelHandlers();
  registerReleaseNoteHandlers();
  registerImportHandlers();
  registerSessionHandlers();
  registerProHandlers();
  registerContextPathsHandlers();
  registerAppUpgradeHandlers();
  registerCapacitorHandlers();

  registerTemplateHandlers();
  registerThemesHandlers();
  registerPortalHandlers();
  registerPromptHandlers();
  registerHelpBotHandlers();
  registerMcpHandlers();
  registerSecurityHandlers();
  registerVisualEditingHandlers();
  registerFreeAgentQuotaHandlers();
  registerPlanHandlers();
  registerAuthHandlers();
  registerEntitlementHandlers();
  registerDesignSystemHandlers();
}
